### ISSUE TITLE
Synchronous checking feature

### ISSUE THREAD

**Issue by cshaa** [MaxArt2501/object-observe#2]
I'm working on an online app that synchronizes object data between peers across the web. It's _that_ kind of apps that run a certain piece of code over and over again. Wait – it's the same kind of app as the `Object.observe` polyfill! The deal is that I need to check the observed object only once a cycle which would be much less computationally expensive than the _dirty checking_ that is used now. Actually it would slow my code down a bit because it would require the checks to run synchronously but the advantages became more noticeable when more simultaneous scripts are used.

The feature I suggest would be used approximately this way:

``` javascript
var obj = {};
var trig = Object.observe(
  obj,
  observer,
  /* additional non-standard flag: */ true
);

function myLoop(){
  if(trig){ //the standard code would result in trig===undefined
    //the polyfill would return a trigger function instead
    trig(); //now all the changes are checked
  }
  requestAnimationFrame(myLoop);
  //do something
}
function observer(changes){
  //do something
}
```

I'm not sure whether it's clear... It would be just an improvement for programmers that understand how the polyfill works.

**Comment by MaxArt2501** [comment]
This polyfill aims to be as spec compliant as possible, so I'm not willing to add any non-standard feature. 
If I were to add such a feature, what would happen in environments that natively supports `Object.observe`? Chrome and the recently released node.js 0.12 throw an error if a third argument is passed to `Object.observe`, so your implementation wouldn't work.
Moreover, `Object.observe` normally returns the observed object itself, which can also be a function (and this made me notice a bug: the polyfill doesn't work on functions; I'll fix it in the next release).  

Hypotetically, defining a function like `Object.checkObjectChanges` would solve this, but then again it would have to be defined for environments that support `Object.observe` and those that don't all alike. That wouldn't be the point of this polyfill, so it won't happen any time soon unless something similar will be defined in the spec, but you are free to use part of the code to implement such feature in your project.

Regarding your case, though, there's a thing that can be said, and another that can be done. First of all, cheer up! Because the check on changes of the properties is actually done _once a frame_, precisely using `requestAnimationFrame`, so it's quite exactly the type of dirty checking you would perform. No performance difference whatsoever (you can have a look at how the internal function `nextFrame` is defined). This is mentioned in the [extendend documentation](../blob/master/doc/index.md).
In other words, it doesn't perform a continuous check, which would clog the thread and make single threaded CPUs become unresponsive. I tried using `setImmediate` when available, or `setTimeout(..., 0)`, but that resulted in the mentioned heavy CPU load.

Secondarily, if you want the change records to be delivered "right here and right now" (i.e. synchronously), that's where `Object.deliverChangeRecords` becomes useful. For example:

``` js
var obj = {};
Object.observe(obj, observer);

function myLoop() {
  // Synchronous check and delivery
  Object.deliverChangeRecords(observer);
  requestAnimationFrame(myLoop);
}
```

Of course, if calling `Object.deliverChangeRecords` is the only thing that `myLoop` does, I'd suggest to ditch it completely and rely on the loop that the polyfill uses internally.

I understand that's not exactly what you want to do, but that's how `Object.observe` behaves.
Wow, I've been quite lengthy, but I hope this helps clarifying your doubts.

**Comment by cshaa** [comment]
Oh, they throw an error?
OK, I believe you.
