### ISSUE TITLE
Fallback to Proxy

### ISSUE THREAD

**Issue by bisubus** [MaxArt2501/object-observe#20]
Can Object.observe polyfill be made to fall back to Proxy?

The fact that Object.observe was deprecated and and dropped in V8 4.9 suggests that Proxy could be used as drop-in replacement, if possible.

**Comment by MaxArt2501** [comment]
Unfortunately, that is not possible, as already explained in the [documentation](https://github.com/MaxArt2501/object-observe/blob/master/doc/index.md#under-the-hood). The problem is that while `Object.observe` watches for changes in a given object, a proxied object catches changes in a _copy_ of the object. Which means that is a change is made on the original object, it won't be caught by the proxied object's handlers.

Anyway, I consider the development of this polyfill as concluded - at least on my part. I'm willing to deliver security fixes only.
More than that, the whole package is deprecated, as `O.o` is gone. Modern web application should head to different approaches than observing an object for changes, namely functional programming. For the rest, `Proxy` is the way to go.

**Comment by bisubus** [comment]
Sorry, I've missed that readme part, thank you for the explanation. I was looking for the library to embrace both Object.observe and Proxy and switch between them, depending on which one is available. Do you have one at your sight by chance?

**Comment by MaxArt2501** [comment]
None that I'm aware of.
And after all, I wouldn't recommend to use `Object.observe` altogether, since it's gone on the sole platform that supported it. And I'm not sure about any package that mixes it with `Proxy`, since we're talking about different approaches to the problem.

My suggestion is to use just `Proxy` objects or, if you have to deal with older platforms, targeted libraries like Polymer's [observe-js](https://github.com/Polymer/observe-js).

If you don't mind, I'm closing this issue. Feel free to comment further, though.

**Comment by bisubus** [comment]
Thanks, you've helped indeed, totally forgot about Polymer's observe-js.
