### ISSUE TITLE
Optimize dirty-checking when only a few properties are observed

### ISSUE THREAD

**Issue by louisameline** [MaxArt2501/object-observe#4]
Hello and thanks for this great lib.

Ok, so sometimes people are only interested in observing one or a few property of an object. The guys over at [Observe-js](https://github.com/polymer/observe-js) made an `PathObserver` class for it, and I allowed that feature too as a second argument in my own library [Observe_evented](https://github.com/louisameline/observe_evented). 

Especially on big objects, there is a gain of time to only dirt-check those properties, instead of every properties of the object. I'm looking for the shim that I'll recommend to my users to work alongside my plugin and yours will just be perfect if it can support that feature too.

The way I see it, it would be nice to call something like `Object.observe(obj, callback, thirdArg, name)` where `name` could be a string or an array of strings (or integers for arrays, but I don't think anyone would ever use that).

Note: Object.observe accepts `undefined` as a third argument if no acceptList is to be passed and does not mind a fourth argument either, it's just ignored. 

You'll tell me, what if `Object.observe()` or `Array.observe()` ever take another option as fourth argument in the future ? Right, that's why I'd like the spec to change to `Object.observe(obj, options, callback)` so it does not change anymore. I'll see if that proposition can be considered (it would also solve the anti-pattern of the callback not being the last parameter). And what if we want to add more options to shims ourselves ? Let's do the same with  `Object.observe(obj, options, callback, shimOptions)`, with `name` being a property of `shimOptions`.

I also read in a closed issue that you won't implement anything that is not standard. In advance for that argument, I would argue that speed is a feature of the native O.o, and that implementing this optimization on dirty-checking would make the shim more standard in a way :)

Thank you for your time.

**Comment by MaxArt2501** [comment]
Thank you for stopping by and for the compliment.

I perfectly understand your point of view. This polyfill indeed is especially good non-performance intensive uses. I haven't done extensive benchmarks - and I promise I'll do some in the future - but if you need to observe thousands of properties and you can't always rely on the native implementation of `Object.observe()`, then it may be better to think other ways for your project to work.

On the other hand, if you're interested in changes in a limited set of properties in an object, one can wonder why those properties aren't kept in a separate object from the others. For example, if you want to object the `foo` and `bar` properties of an object, but there other dozens properties you don't care about, the object itself is probably badly designed (somebody said "DOM nodes"?).

The only objects that can actually defy this line of reasoning are arrays. You may just want to observe an array's length, or changes in selected items of the array. For this and similar cases the property checker needs to filter the observable properties using a whitelist of names. Currently, the checker doesn't work like that: it uses a blacklist in the case the observed item is a function, and nothing else. In short, that part has to be rewritten. Not a biggie, but here it comes the dilemma.

As you noticed, I said I'm not willing to add anything that's not standard, and that's because:
1. it's a slippery slope: if I were to add every nice thing that it comes to mind, it could clog the entire project;
2. _specs may change_: what if they will actually add a forth argument to `Object.observe()`? It would be a disaster. We're talking about a feature of EcmaScript _7_, and much can change in the future.

What you're aiming for is not a polyfill for `Object.observe` than includes a dirty checker, but a dirty checker that can take advantage of the native `Object.observe` :) And that's indeed what Observe-js does.

Anyway, this position isn't definitive: I'm always open to new takes on the subject.

Good catch on the accept list argument, will be fixed in the next commit.

**Comment by louisameline** [comment]
What a pleasure to read you :)

I totally understand and have only respect for your wish to do things the right way.

Compromises can be left to forks too, for people who understand the ins and outs. And you're right, it might just not be worth it. I don't have a definitive position on it either, we'll have to see how people use these things.

Thanks again.
